// Lease agreement text — Vietnamese (Tiếng Việt)
export const LEASE_VI = {
  title: "HỢP ĐỒNG THUÊ NHÀ Ở",
  subtitle: "pi2pi.io — Giao thức thuê nhà phi tập trung",
  contractNo: "Hợp đồng số {contractNo}",
  dateOfExecution: "Ngày ký kết: {signedDate}",
  s0_title: "0. TUYÊN BỐ VÀ ĐỒNG THUẬN CỦA CÁC BÊN",
  s0_intro: "Khi ký Hợp đồng này bằng chữ ký mật mã từ ví blockchain, mỗi Bên xác nhận và đồng ý những điều sau:",
  s0_1_title: "0.1. Tự nguyện và năng lực hành vi",
  s0_1: "Các Bên giao kết Hợp đồng này một cách tự nguyện, theo ý chí của mình, có đủ năng lực hành vi và phán đoán, hiểu rõ bản chất, hậu quả và rủi ro của các nghĩa vụ được đảm nhận.",
  s0_2_title: "0.2. Xác minh song phương",
  s0_2: "Các Bên đã tự kiểm tra giấy tờ tùy thân và giấy tờ sở hữu của bên đối tác, được tải lên giao thức dưới dạng mã hóa (IPFS với tham chiếu hash on-chain), và chấp nhận là đầy đủ để giao kết Hợp đồng này. Đơn vị Vận hành giao thức không thực hiện việc xác minh giấy tờ. Chữ ký mật mã từ ví của mỗi Bên là sự xác nhận rõ ràng rằng việc kiểm tra đã hoàn tất.",
  s0_3_title: "0.3. Hiểu biết về công nghệ",
  s0_3: "Các Bên hiểu rằng Hợp đồng này được thực thi qua smart contract trên blockchain, các điều khoản được ghi on-chain và không thể bị sửa đổi đơn phương sau khi ký, và chữ ký mật mã từ ví là hành vi có hiệu lực pháp lý ràng buộc.",
  s0_4_title: "0.4. Vị trí của Đơn vị Vận hành Giao thức",
  s0_4_intro: "Đơn vị vận hành giao thức pi2pi.io (\"Đơn vị Vận hành\") không phải là một Bên của Hợp đồng này. Đơn vị Vận hành cung cấp cho các Bên quyền truy cập hạ tầng phần mềm phi tập trung (smart contract, giao diện người dùng, lưu trữ tài liệu mã hóa), được thực thi tự động theo các quy tắc định sẵn. Đơn vị Vận hành:",
  s0_4_bullets: [
    "không cung cấp dịch vụ tài chính;",
    "không giữ, lưu trữ hoặc chuyển tiền của các Bên;",
    "không cung cấp dịch vụ pháp lý, tư vấn hoặc trung gian;",
    "không xác minh danh tính các Bên, tính xác thực của giấy tờ hoặc tình trạng thực tế của Tài sản;",
    "không đóng vai trò trọng tài, hòa giải viên hoặc đại diện của bất kỳ Bên nào.",
  ],
  s0_4_footer: "Toàn bộ tiền của các Bên, trong suốt thời hạn Hợp đồng này, được kiểm soát duy nhất bởi smart contract tự động, có logic định sẵn và sẵn sàng để các Bên xem xét.",
  s0_5_title: "0.5. Phí giao thức",
  s0_5: "Ba mươi phần trăm (30%) lợi suất phát sinh trên tiền cọc trong thời gian được đặt vào giao thức cho vay phi tập trung Aave v2 (bên thứ ba) được chuyển vào treasury giao thức làm phí sử dụng giao thức. Khoản phí này không phải là thù lao cho Đơn vị Vận hành cho dịch vụ được cung cấp; không phải là chi phí lưu trữ hoặc quản lý tiền của các Bên; là phí truy cập hạ tầng phần mềm của giao thức và bù đắp chi phí phát triển, triển khai và bảo trì. Các Bên xác nhận đã được thông báo về mức phí trước khi ký Hợp đồng này và cho rằng phí là hợp lý và chấp nhận được.",
  s0_6_title: "0.6. Chấp nhận rủi ro",
  s0_6_intro: "Các Bên chấp nhận và miễn trừ trách nhiệm cho Đơn vị Vận hành đối với:",
  s0_6_bullets: [
    "rủi ro của smart contract bên thứ ba (bao gồm Aave v2);",
    "rủi ro USDC depeg hoặc mất giá trị;",
    "rủi ro blockchain (fork, gián đoạn mạng, chậm giao dịch);",
    "rủi ro mất, lộ hoặc trộm khóa riêng của các Bên;",
    "hành động, không hành động hoặc thiếu thiện chí của bên đối tác;",
    "tính xác thực, tính cập nhật hoặc độ chính xác của giấy tờ do bên đối tác tải lên;",
    "tình trạng thực tế của Tài sản và sự khớp với mô tả trong Hợp đồng.",
  ],
  s0_7_title: "0.7. Giải quyết khiếu nại",
  s0_7: "Mọi khiếu nại và tranh chấp giữa các Bên được giải quyết duy nhất giữa các Bên theo phương thức quy định tại Mục 6 Hợp đồng này và, khi cần thiết, theo thủ tục tố tụng tại tòa án theo Mục 6.9. Đơn vị Vận hành không phải là một bên trong bất kỳ tranh chấp nào và không tham gia vào việc giải quyết.",
  s0_8_title: "0.8. Nhân sự kỹ thuật của Đơn vị Vận hành",
  s0_8: "Cá nhân thực hiện việc phát triển, triển khai và bảo trì kỹ thuật hạ tầng phần mềm của giao thức chỉ thực hiện chức năng kỹ thuật nhằm duy trì khả năng vận hành của mã phần mềm. Những cá nhân này không phải là một Bên của Hợp đồng này, không tham gia vào việc thực thi các điều khoản, không cung cấp cho các Bên dịch vụ pháp lý, tài chính, tư vấn hoặc trung gian, không thực hiện xác minh danh tính, kiểm tra giấy tờ, định giá Tài sản, hòa giải tranh chấp hoặc bất kỳ hành vi nào liên quan đến nội dung của Hợp đồng, và không có quyền truy cập vào tiền cọc của các Bên.",
  s1_title: "1. CÁC BÊN",
  landlord: "BÊN CHO THUÊ",
  tenant: "BÊN THUÊ",
  fullLegalName: "Họ tên đầy đủ theo giấy tờ",
  walletAddress: "Địa chỉ ví blockchain (định danh pháp lý)",
  idDocument: "Giấy tờ tùy thân",
  s2_title: "2. TÀI SẢN",
  address: "Địa chỉ",
  conditionNote: "Tình trạng Tài sản (ảnh và danh sách đồ đạc) được ghi nhận tại thời điểm ký Hợp đồng này — xem Phụ lục B.",
  itemsIncluded: "Đồ đạc kèm theo nhà thuê: {count} mục — xem Phụ lục C.",
  ownershipCert: "Giấy chứng nhận quyền sở hữu",
  s3_title: "3. ĐIỀU KHOẢN HỢP ĐỒNG",
  startDate: "Ngày bắt đầu",
  endDate: "Ngày kết thúc",
  duration: "Thời hạn",
  monthlyRent: "Tiền thuê hàng tháng",
  paymentSchedule: "Lịch thanh toán",
  paymentScheduleValue: "Hàng tháng kể từ ngày bắt đầu",
  paymentMethod: "Phương thức thanh toán",
  paymentMethodValue: "USDC stablecoin trên blockchain Arc Testnet",
  gracePeriod: "Thời hạn gia hạn tiền thuê",
  gracePeriodValue: "{days} ngày dương lịch",
  leaseGrantTitle: "Chuyển giao quyền thuê và nghĩa vụ cốt lõi",
  leaseGrant: "Bên Cho Thuê cho Bên Thuê thuê Bất Động Sản, và Bên Thuê chấp nhận Bất Động Sản để ở, theo thời hạn thuê và tiền thuê hàng tháng nêu trong Hợp Đồng này.\n\nBên Thuê phải thanh toán tiền thuê hàng tháng bằng USDC theo lịch thanh toán nêu trên. Các Bên thừa nhận rằng tiền cọc, tình trạng thanh toán, thời hạn và hoàn trả được điều chỉnh bởi bản ghi smart contract liên kết với Hợp Đồng này.\n\nTình trạng Bất Động Sản, ảnh chụp đã tải lên, giấy tờ sở hữu, giấy tờ tùy thân và danh sách kiểm kê được đưa vào Hợp Đồng này như phụ lục. Bằng việc ký, mỗi Bên xác nhận đã xem xét các phụ lục có sẵn trước khi ký kết.\n\nKhi hết hạn thuê, Bên Thuê phải trả lại Bất Động Sản trong tình trạng tương tự, ngoại trừ hao mòn bình thường, theo quy trình kiểm tra và giải quyết tranh chấp trong Hợp Đồng này.",
  s4_title: "4. TIỀN CỌC VÀ ESCROW",
  s4_intro: "Toàn bộ tiền cọc được giữ trong escrow (giữ tiền an toàn) bằng smart contract phi lưu ký. Không Bên nào, kể cả Đơn vị Vận hành, có thể đơn phương truy cập hoặc chuyển hướng tiền cọc.",
  commitmentDeposit: "Commitment Deposit (Bên Thuê)",
  commitmentNote: "Trả lại khi hợp đồng kết thúc không khiếu nại. Chuyển cho Bên Cho Thuê khi trễ tiền thuê hoặc Bên Thuê đơn phương chấm dứt.",
  hostingDeposit: "Hosting Deposit (Bên Cho Thuê)",
  hostingNote: "Trả lại khi hợp đồng kết thúc không khiếu nại. Chuyển cho Bên Thuê khi bị buộc trả nhà trái pháp luật hoặc Bên Cho Thuê đơn phương chấm dứt.",
  propDeposit: "Tiền cọc tài sản (Bên Thuê)",
  propNote: "Giữ trong PropDepEscrow. Cửa sổ kiểm tra 7 ngày sau khi hợp đồng kết thúc. Trả lại nếu không có khiếu nại hư hỏng.",
  yieldTitle: "Lợi suất staking",
  yieldNote: "70% — chia đều giữa Bên Thuê và Bên Cho Thuê; 30% — phí sử dụng giao thức.",
  smartContractAddr: "Địa chỉ smart contract",
  depositedBy: "Bên gửi cọc",
  amount: "Số tiền",
  s5_title: "5. GIẤY TỜ ĐÃ NỘP VÀ XÁC MINH",
  uploaded: "Đã tải lên",
  notProvided: "Chưa cung cấp",
  s6_title: "6. GIẢI QUYẾT TRANH CHẤP VÀ CHẤM DỨT",
  s6_1_title: "6.1. Chấm dứt sớm — Đồng thuận",
  s6_1: "Cả hai Bên ký giao dịch chấm dứt đồng thuận on-chain. Mỗi Bên nhận lại toàn bộ tiền cọc của mình. Không áp dụng tiền phạt.",
  s6_2_title: "6.2. Chấm dứt sớm — Đơn phương với tiền bồi thường đã thỏa thuận",
  s6_2: "Bất kỳ Bên nào có thể đơn phương chấm dứt Hợp đồng này. Tiền cọc của Bên khởi tạo tự động chuyển cho bên đối tác làm tiền bồi thường đã thỏa thuận trước. Việc thực thi cần một giao dịch on-chain duy nhất; không cần chữ ký của bên đối tác.",
  s6_3_title: "6.3. Chấm dứt sớm — Có tranh chấp",
  s6_3: "Khi một Bên yêu cầu tiền cọc của bên đối tác, cả hai tiền cọc bị đóng băng sáu mươi (60) ngày dương lịch. Bên đối tác có thể: Chấp nhận (tiền cọc cho bên khiếu nại), Nhượng bộ (tiền cọc cho bên đối tác), hoặc Chờ (tiền cọc trả lại cho mỗi bên sau 60 ngày).",
  s6_4_title: "6.4. Hạn trả nhà",
  s6_4: "Bên Thuê khởi tạo: 3 ngày dương lịch. Bên Cho Thuê khởi tạo: 7 ngày dương lịch.",
  s6_5_title: "6.5. Tiền cọc tài sản — Cửa sổ kiểm tra",
  s6_5: "Cửa sổ kiểm tra 7 ngày sau khi hợp đồng kết thúc. Không có khiếu nại → toàn bộ tiền cọc tự động trả lại Bên Thuê.",
  s6_6_title: "6.6. Khiếu nại hư hỏng tài sản",
  s6_6: "Bên Cho Thuê có thể yêu cầu đến mức Tiền cọc tài sản. Bên Thuê có 3 ngày để Chấp nhận hoặc Phản đối. Nếu phản đối, Bên Cho Thuê nộp tiền bảo đảm; áp dụng đóng băng 60 ngày.",
  s6_7_title: "6.7. Trễ tiền thuê",
  s6_7: "Áp dụng thời hạn gia hạn. Bên Cho Thuê có thể gia hạn đến 14 ngày. Sau khi hết hạn, Commitment Deposit của Bên Thuê chuyển cho Bên Cho Thuê.",
  s6_8_title: "6.8. Kết thúc hợp đồng",
  s6_8: "Khi hết hạn thuê, tiền cọc được trả lại và hợp đồng được đóng. Để tiếp tục thuê, các bên phải ký hợp đồng mới.",
  s6_9_title: "6.9. Luật áp dụng và thẩm quyền",
  s6_9: "Áp dụng lex rei sitae (luật nơi Tài sản tọa lạc). Tranh chấp được đưa ra tòa án có thẩm quyền tại nơi Tài sản tọa lạc. Mọi ghi chép on-chain được chấp nhận làm bằng chứng. Chữ ký EIP-191 được công nhận tương đương chữ ký viết tay.",
  s6_10_title: "6.10. Xác nhận về Stablecoin",
  s6_10: "Mọi khoản tiền tính bằng USDC. Các Bên đồng ý USDC đáp ứng mọi nghĩa vụ thanh toán dù không phải là tiền pháp định.",
  s6_11_title: "6.11. Thẩm quyền của Smart Contract",
  s6_11: "Tiền được quản lý bởi logic smart contract. Việc giải phóng tiền là tự động và không phụ thuộc vào hành động đơn phương của bất kỳ Bên nào.",
  s7_title: "7. ĐIỀU KHOẢN BỔ SUNG",
  s7_1_title: "7.1. Mục đích sử dụng được phép",
  s7_1: "Chỉ dùng cho mục đích để ở. Không sử dụng thương mại, cho thuê lại ngắn hạn hoặc các hoạt động trái pháp luật.",
  s7_2_title: "7.2. Tiện ích",
  s7_2: "Bên Thuê chịu trách nhiệm chi trả tiện ích trừ khi có thỏa thuận khác. Thanh toán thực hiện off-chain cho nhà cung cấp.",
  s7_3_title: "7.3. Bảo trì",
  s7_3: "Bên Thuê: bảo trì thường xuyên và sửa chữa nhỏ. Bên Cho Thuê: sửa chữa kết cấu và hệ thống. Hao mòn thông thường không phải là cơ sở để khiếu nại hư hỏng.",
  s7_4_title: "7.4. Bảo vệ dữ liệu",
  s7_4: "Giấy tờ được mã hóa và lưu trên IPFS. Đơn vị Vận hành xử lý dữ liệu chỉ cho mục đích vận hành giao thức.",
  s7_5_title: "7.5. Ngôn ngữ",
  s7_5: "Bản tiếng Anh là bản gốc có giá trị pháp lý. Bản dịch chỉ cung cấp cho tiện lợi tham khảo.",
  s7_6_title: "7.6. Tính độc lập của các điều khoản",
  s7_6: "Các điều khoản vô hiệu được thay thế bằng điều khoản hợp lệ tương đương gần nhất. Các điều khoản còn lại không bị ảnh hưởng.",
  s7_7_title: "7.7. Toàn bộ Hợp đồng",
  s7_7: "Hợp đồng này cùng với ghi chép on-chain tạo thành toàn bộ thỏa thuận giữa các Bên.",
  s8_title: "8. CHỮ KÝ MẬT MÃ",
  signatureMethod: "Phương thức ký: personal_sign (EIP-191)",
  signedAt: "Ký lúc",
  notYetSigned: "Chưa ký",
  verification: "XÁC MINH",
  agreementId: "Mã Hợp đồng",
  createdOnChain: "Tạo on-chain",
  verify: "Xác minh",
  documentHash: "SHA-256 của tài liệu",
  footer: "Hợp đồng này được tạo và ký qua giao thức thuê nhà phi tập trung pi2pi.io. Ghi chép on-chain là phiên bản có giá trị pháp lý.",
};
